package net.nweber.plex.parsers.xml
{
	import net.nweber.plex.parsers.IShowSectionParser;
	import net.nweber.plex.valueObjects.Show;
	
	/**
	 * 
	 * 
	 * @author Nathan Weber
	 */
	public class ShowSectionParser implements IShowSectionParser
	{
		//----------------------------------------
		//
		// Public Methods
		//
		//----------------------------------------
		/*
		<MediaContainer size="78" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1343722542" nocache="1" sortAsc="1" viewGroup="show" viewMode="458803" art="/:/resources/show-fanart.jpg" title1="TV Shows" title2="All Shows" identifier="com.plexapp.plugins.library">
			<Directory ratingKey="1465" key="/library/metadata/1465/children" studio="Tokyo Broadcasting System" type="show" title="Amagami SS" contentRating="TV-G" summary="A second-year high school boy finds himself uneasy during Christmas time due to an experience in the past. However, this year at Christmas, he gets his last chance to ask out a graduating female senior named Haruka Morishima — or one of several other classmates. The story of the anime will be arranged in an omnibus format, with each heroine getting her own version of the story animated. Each heroine will sing her own version of the ending theme song." index="1" rating="8.5" year="2010" thumb="/library/metadata/1465/thumb?t=1343958612" art="/library/metadata/1465/art?t=1343958612" banner="/library/metadata/1465/banner?t=1343958612" theme="/library/metadata/1465/theme?t=1343958612" duration="1500000" originallyAvailableAt="2010-07-02" leafCount="38" viewedLeafCount="0" addedAt="1343958113" updatedAt="1343958612">
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="737" key="/library/metadata/737/children" type="show" title="Astarotte's Toy" summary="While job hunting, Naoya is taken by a mysterious girl to a magical land where he is installed in the harem of the succubus Queen Lotte. Thanks to trauma from her childhood, Lotte hates men and surrounds herself with lots of other women, who all have quirks of their own. In spite of her selfishness, when Naoya learns that Lotte is really quite lonely he agrees to stay in her world...if he can bring his daughter Asuha with him." index="1" rating="7.3" year="2011" thumb="/library/metadata/737/thumb?t=1343871177" art="/library/metadata/737/art?t=1343871177" banner="/library/metadata/737/banner?t=1343871177" duration="1500000" originallyAvailableAt="2011-04-10" leafCount="13" viewedLeafCount="13" addedAt="1343871134" updatedAt="1343871177">
			  <Genre tag="Animation"/>
			  <Genre tag="Comedy"/>
			</Directory>
			<Directory ratingKey="761" key="/library/metadata/761/children" studio="Tokyo MX" type="show" title="B Gata H Kei - Yamada’s First Time" summary="The story revolves around a sexually inexperienced schoolgirl who is aiming to get 100 sex-friends after entering High-School. But she always freaks out, because she thinks she would be laughed at for her virginity. That's why she searches for a virgin-guy aswell, he would be inexperienced aswell, so he wouldn't look down on her. One day, by chance, she met such a guy, whom she later realizes is sitting next to her in school! Fate? So her seductions begin..." index="1" rating="8.8" year="2010" thumb="/library/metadata/761/thumb?t=1343872221" art="/library/metadata/761/art?t=1343872221" banner="/library/metadata/761/banner?t=1343872221" duration="1500000" originallyAvailableAt="2010-04-02" leafCount="12" viewedLeafCount="0" addedAt="1343872175" updatedAt="1343872221">
			  <Genre tag="Animation"/>
			  <Genre tag="Comedy"/>
			</Directory>
			<Directory ratingKey="1513" key="/library/metadata/1513/children" studio="Tokyo MX" type="show" title="Bakemonogatari" contentRating="TV-PG" summary="Bakemonogatari centres on Araragi Koyomi, a third year high school student who is almost human again after briefly becoming a vampire. One day, a classmate named Senjougahara Hitagi, who infamously never talks to anyone, falls down the stairs into Koyomi's arms. He discovers that Hitagi weighs next to nothing, in defiance of physics. After being threatened by her, Koyomi offers her help, and introduces her to Oshino Meme, a middle-aged homeless man who helped him stop being a vampire." index="1" rating="9.4" year="2009" thumb="/library/metadata/1513/thumb?t=1343960158" art="/library/metadata/1513/art?t=1343960158" banner="/library/metadata/1513/banner?t=1343960158" theme="/library/metadata/1513/theme?t=1343960158" duration="1500000" originallyAvailableAt="2009-07-03" leafCount="15" viewedLeafCount="0" addedAt="1343960087" updatedAt="1343960158">
			  <Genre tag="Animation"/>
			  <Genre tag="Comedy"/>
			</Directory>
			<Directory ratingKey="1552" key="/library/metadata/1552/children" studio="NHK" type="show" title="Bakuman" summary="The series follows talented artist Moritaka Mashiro and aspiring writer Akito Takagi, two ninth grade boys who wish to become mangaka." index="1" rating="8" year="2010" thumb="/library/metadata/1552/thumb?t=1343961277" art="/library/metadata/1552/art?t=1343961277" banner="/library/metadata/1552/banner?t=1343961277" duration="1500000" originallyAvailableAt="2010-10-02" leafCount="50" viewedLeafCount="0" addedAt="1343961198" updatedAt="1343961277">
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="1605" key="/library/metadata/1605/children" studio="TV Tokyo" type="show" title="Battle Athletes Victory" summary="The year is 4998. Girls from all over the galaxy come together to train for the title of Cosmo Beauty in a bevy of athletic events. Akari, our heroine, wants to go to University Satellite where her mother once went and won the title. That is, if her bad luck will give her a chance! Add into the mix a cutthroat competition between star athletes and complicated midterms, and you have some rough competition revolving around bizarre plots and insane hijinks! Oh, and did we mention the field events? Bring your hard hats everyone, as the galaxy will never be the same!" index="1" rating="10" year="1997" thumb="/library/metadata/1605/thumb?t=1343961265" art="/library/metadata/1605/art?t=1343961265" banner="/library/metadata/1605/banner?t=1343961265" duration="1500000" originallyAvailableAt="1997-10-01" leafCount="32" viewedLeafCount="32" addedAt="1343961207" updatedAt="1343961265">
			  <Genre tag="Action and Adventure"/>
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="2150" key="/library/metadata/2150/children" studio="Tokyo MX" type="show" title="Black Lagoon" contentRating="TV-MA" summary="Okajima Rokuro - now known almost exclusively as 'Rock' - was once a typical, put-upon Japanese businessman. Then, on a routine business trip, he was kidnapped and ransomed by the Lagoon Company: a band of mercenary pirates operating out of the crime-riddled city of Roanapur. Abandoned by his bosses, he joined the Lagoon Company. Now he must try and stay afloat amongst the ever-shifting politics of the criminal underworld, while simultaneously avoiding death at the hands of his quick-tempered, gun-toting co-worker, 'Two Hand' Revy. " index="1" rating="9.1" year="2006" thumb="/library/metadata/2150/thumb?t=1344048504" art="/library/metadata/2150/art?t=1344048504" banner="/library/metadata/2150/banner?t=1344048504" theme="/library/metadata/2150/theme?t=1344048504" duration="1500000" originallyAvailableAt="2006-04-09" leafCount="36" viewedLeafCount="0" addedAt="1344047024" updatedAt="1344048504">
			  <Genre tag="Action and Adventure"/>
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="2191" key="/library/metadata/2191/children" type="show" title="Captain Herlock - The endless odyssey" summary="On an archaelogical mission to the end of the known universe, Professor Daiba unwitting unleashes an ancient horror from its confines. Five years later the malevolent alien force sets in motion a plan which reunites the various crewmembers of the Arcadia to sail the stars once more as well as bring Tadashi Daiba to meet Harlock for the first time (again)." index="1" rating="7.5" year="2003" thumb="/library/metadata/2191/thumb?t=1344048493" banner="/library/metadata/2191/banner?t=1344048493" duration="1500000" originallyAvailableAt="2003-10-07" leafCount="13" viewedLeafCount="0" addedAt="1344047257" updatedAt="1344048493">
			  <Genre tag="Animation"/>
			  <Genre tag="Science-Fiction"/>
			</Directory>
			<Directory ratingKey="2252" key="/library/metadata/2252/children" type="show" title="Carnival Phantasm" summary="'Carnival Phantasm' is an adaption of the Manga 'Take Moon' by Type-Moon's Eri Takenashi, to celebrate Type-Moon's 10th Anniversary.&#xA;&#xA;In this show you'll see parodies and new stories loosely based on Type-Moon's original works like Melty Blood, Fate/Stay Night, Tsukihime and more." index="1" rating="9" year="2011" thumb="/library/metadata/2252/thumb?t=1344053915" art="/library/metadata/2252/art?t=1344053915" banner="/library/metadata/2252/banner?t=1344053915" duration="900000" originallyAvailableAt="2011-08-12" leafCount="14" viewedLeafCount="0" addedAt="1344053750" updatedAt="1344053915">
			  <Genre tag="Animation"/>
			  <Genre tag="Comedy"/>
			</Directory>
			<Directory ratingKey="1640" key="/library/metadata/1640/children" studio="Fuji TV" type="show" title="Chrono Crusade" summary="It is after the Great War and the U.S. is experiencing an economic prosperity unlike anything ever seen before.  However, all is not well, as the occurences of the ocult and devil-worshippers begin to sprout up all over the country.  Enter the Magdalene Order, a special group of excorsist that use tradional methods (holy water and special metal) and infused them into the technology of the time to battle these demons and their summoners. This is the story of Rosette Christopher, a young excorsist and her close friend Chrono, a demon with a dark history, as they go on a quest to find and rescue Rosette's younger brother, Joshua, from the clutches of evil. This is going to be a trip" index="1" rating="8.3" year="2003" thumb="/library/metadata/1640/thumb?t=1343961281" art="/library/metadata/1640/art?t=1343961281" banner="/library/metadata/1640/banner?t=1343961281" duration="1500000" originallyAvailableAt="2003-10-13" leafCount="24" viewedLeafCount="24" addedAt="1343961218" updatedAt="1343961281">
			  <Genre tag="Animation"/>
			  <Genre tag="Fantasy"/>
			</Directory>
			<Directory ratingKey="1666" key="/library/metadata/1666/children" studio="MBS" type="show" title="Code Geass: Lelouch of the Rebellion" contentRating="TV-14" summary="Japan has been invaded and conquered by the Britannic Empire. Japan is now known as &quot;Area 11&quot; and it's citizens known as &quot;elevens&quot;. The Britannic Empire takes away Japan's autonomous power and imposes its rule. The Britannic Empire enforces its rule through the use of &quot;Nightmares&quot;. The Empire's rule has never faltered, but cracks have begun to show..." index="1" rating="9.4" year="2006" thumb="/library/metadata/1666/thumb?t=1343965082" art="/library/metadata/1666/art?t=1343965082" banner="/library/metadata/1666/banner?t=1343965082" theme="/library/metadata/1666/theme?t=1343965082" duration="1500000" originallyAvailableAt="2006-10-05" leafCount="50" viewedLeafCount="50" addedAt="1343964393" updatedAt="1343965082">
			  <Genre tag="Action and Adventure"/>
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="2795" key="/library/metadata/2795/children" studio="MTV" type="show" title="Daria" contentRating="TV-PG" summary="The people of Lawndale just don't get Daria Morgendorffer. She's cool with that. See, Daria was born alienated, and now she's just trying to make it through high school with as little human contact as possible. Popularity, friends, activities... whatever. Daria lacks enthusiasm, but she makes up for it with sarcasm. Daria is the spin-off of MTV's most sucessful cartoon, Beavis and Butt-Head. " index="1" rating="8.7" year="1997" thumb="/library/metadata/2795/thumb?t=1344313608" art="/library/metadata/2795/art?t=1344313608" banner="/library/metadata/2795/banner?t=1344313608" theme="/library/metadata/2795/theme?t=1344313608" duration="1800000" originallyAvailableAt="1997-03-01" leafCount="69" viewedLeafCount="1" addedAt="1344313517" updatedAt="1344313608">
			  <Genre tag="Animation"/>
			  <Genre tag="Comedy"/>
			</Directory>
			<Directory ratingKey="43" key="/library/metadata/43/children" studio="Animax" type="show" title="Darker than Black" contentRating="TV-14" summary="In Tokyo, a bizarre field appears that is impossible to analyze. Coinciding with this &quot;Hell's Gate&quot; is the appearance of humans possessing new forms and new powers. These criminally insane beings are fearfully called &quot;Contractors&quot; and sometimes brutally murder others." index="1" rating="9" year="2007" thumb="/library/metadata/43/thumb?t=1343788565" art="/library/metadata/43/art?t=1343788565" banner="/library/metadata/43/banner?t=1343788565" duration="1500000" originallyAvailableAt="2007-04-06" leafCount="42" viewedLeafCount="0" addedAt="1343788541" updatedAt="1343788565">
			  <Genre tag="Action and Adventure"/>
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="256" key="/library/metadata/256/children" type="show" title="Deadman Wonderland" contentRating="TV-14" summary="A massive earthquake ravaged Japan's mainland and destroyed most of Tokyo, sinking three-quarters of it into the ocean. Ten years later, the story starts with Igarashi Ganta, a seemingly ordinary, unassuming middle school student attending Nagano Prefecture's middle school. An escapee, a survivor of the great earthquake, Ganta has no memories of the tragedy and has lived a simple, normal life. This all changes one day when a strange man covered in blood and crimson armour appears, floating, out of his classroom windows. Smirking madly, this Red Man massacres Ganta's entire class and, instead of killing him, embeds a red crystal shard in his chest. Within days of the massacre, Ganta is declared the sole suspect and, following a suspiciously quick trial, is sentenced to life imprisonment in Deadman Wonderland, a massive theme-park-like prison." index="1" rating="8.9" year="2011" thumb="/library/metadata/256/thumb?t=1343795771" art="/library/metadata/256/art?t=1343795771" banner="/library/metadata/256/banner?t=1343795771" duration="1500000" originallyAvailableAt="2011-04-17" leafCount="13" viewedLeafCount="13" addedAt="1343795721" updatedAt="1343795771">
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="367" key="/library/metadata/367/children" studio="Tokyo Broadcasting System" type="show" title="Dream Eater Merry" summary="High school student Fujiwara Yumeji possesses the unusual ability to see other people's dreams. One day, he meets Merry who had wandered from the Dream World into the Real World. This meeting raises many questions for Yumeji. Who exactly is Merry? What is the Dream World and what are Nightmares? What purpose do the Nightmares have for entering the Real World?" index="1" rating="6.3" year="2011" thumb="/library/metadata/367/thumb?t=1343795780" art="/library/metadata/367/art?t=1343795780" banner="/library/metadata/367/banner?t=1343795780" duration="1500000" originallyAvailableAt="2011-01-06" leafCount="13" viewedLeafCount="0" addedAt="1343795729" updatedAt="1343795780">
			  <Genre tag="Action and Adventure"/>
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="2733" key="/library/metadata/2733/children" studio="Tokyo MX" type="show" title="Dusk Maiden of Amnesia" summary="The story revolves around a first-year high school student, Teiichi Niiya who had just enrolled at Seikyou Private Academy. When he gets lost in one of the school's old building, he meets a girl named Yuuko Kanoe who reveals herself as a ghost with no memories. Teiichi then decides to investigate her death by looking through the school's seven mysteries revolving around her. Throughout the story, Teiichi and Yuuko discover the truth about these ghost stories and help those who are troubled." index="1" rating="8.5" year="2012" thumb="/library/metadata/2733/thumb?t=1344313614" art="/library/metadata/2733/art?t=1344313614" banner="/library/metadata/2733/banner?t=1344313614" duration="1500000" originallyAvailableAt="2012-04-08" leafCount="12" viewedLeafCount="0" addedAt="1344313504" updatedAt="1344313614">
			  <Genre tag="Animation"/>
			  <Genre tag="Comedy"/>
			</Directory>
			<Directory ratingKey="1719" key="/library/metadata/1719/children" studio="Fuji TV" type="show" title="Eden of the East" contentRating="TV-14" summary="On November 22, 2010 ten missiles strike Japan. However, this unprecedented terrorist act, later to be called as &quot;Careless Monday,&quot; does not result in any apparent victims, and is soon forgotten by almost everyone. Then, 3 months later... Saki Morimi is a young woman currently in the United States of America on her graduation trip. But just when she is in front of the White House, Washington DC, she gets into trouble, and only the unexpected intervention of one of her fellow countrymen saves her. However, this man, who introduces himself as Akira Takizawa, is a complete mystery. He appears to have lost his memory. and he is stark naked, except for the gun he holds in one hand, and the mobile phone he's holding with the other hand. A phone that is charged with 8,200,000,000 yen in digital cash." index="1" rating="9.2" year="2009" thumb="/library/metadata/1719/thumb?t=1343965067" art="/library/metadata/1719/art?t=1343965067" banner="/library/metadata/1719/banner?t=1343965067" theme="/library/metadata/1719/theme?t=1343965067" duration="1500000" originallyAvailableAt="2009-04-09" leafCount="13" viewedLeafCount="13" addedAt="1343964734" updatedAt="1343965067">
			  <Genre tag="Animation"/>
			  <Genre tag="Drama"/>
			</Directory>
			<Directory ratingKey="1530" key="/library/metadata/1530/children" studio="AT-X" type="show" title="Elfen Lied" contentRating="TV-MA" summary="The diclonius, otherwise known as a two-horned human, are mutants of the human species, and may well be the next step in human evolution. The diclonius have horns and strong telekinetic powers represented by &quot;vectors&quot;. However with this great power, they can easily destroy the human race. Fearful of their power, humans quarantined the diclonius into secret research facilities to study. However, in a freak accident, a enraged female diclonius escaped, killing many guards in the process. While escaping, she is shot in the head, and falls into the ocean. As a result she has waves of amnesia. Later, she washes ashore. There, she meets two people named Kouta and Yuka, who name the female diclonius &quot;Nyuu&quot;, after the only word she can say. They decide to watch after her, but of course, the research facility can't have this, and begin trying to retrieve her by any means necessary." index="1" rating="9.1" year="2006" thumb="/library/metadata/1530/thumb?t=1343960126" art="/library/metadata/1530/art?t=1343960126" banner="/library/metadata/1530/banner?t=1343960126" theme="/library/metadata/1530/theme?t=1343960126" duration="1500000" originallyAvailableAt="2006-01-01" leafCount="13" viewedLeafCount="0" addedAt="1343960090" updatedAt="1343960126">
			  <Genre tag="Animation"/>
			  <Genre tag="Drama"/>
			</Directory>
			<Directory ratingKey="2619" key="/library/metadata/2619/children" studio="Tokyo Broadcasting System" type="show" title="Fate/Stay Night" summary="Shirou Emiya lost his parents in a fire when he was young and was later adopted by the sorcerer Kiritsugu Emiya. Shirou is drawn into the Holy Grail War summons a female &quot;Servant&quot; known as Saber to protect him and obtain the Holy Grail." index="1" rating="9" year="2006" thumb="/library/metadata/2619/thumb?t=1344313605" art="/library/metadata/2619/art?t=1344313605" banner="/library/metadata/2619/banner?t=1344313605" theme="/library/metadata/2619/theme?t=1344313605" duration="1500000" originallyAvailableAt="2006-01-06" leafCount="53" viewedLeafCount="0" addedAt="1344313476" updatedAt="1344313605">
			  <Genre tag="Action and Adventure"/>
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="871" key="/library/metadata/871/children" studio="Fuji TV" type="show" title="Fractale" summary="The story takes place on an island, where a Fractale System is beginning to collapse. One day, Clain finds an injured girl called Phryne under a cliff. She disappears leaving a pendant. Clain sets out for a journey with the girl-shaped avatar Nessa to look for Phryne and discovers the secret of the Fractale System." index="1" rating="7.7" year="2011" thumb="/library/metadata/871/thumb?t=1343874998" art="/library/metadata/871/art?t=1343874998" banner="/library/metadata/871/banner?t=1343874998" theme="/library/metadata/871/theme?t=1343874998" duration="1500000" originallyAvailableAt="2011-01-14" leafCount="11" viewedLeafCount="0" addedAt="1343874952" updatedAt="1343874998">
			  <Genre tag="Action and Adventure"/>
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="1882" key="/library/metadata/1882/children" studio="Animax" type="show" title="Fullmetal Alchemist" summary="&quot;Humankind cannot gain anything without first giving something in return. To obtain, something of equal value must be lost. That is Alchemy's first law of Equivalent Exchange. In those days, we really believed that to be the world's one, and only, truth.&quot;  &#xA;-Alphonse Elric &#xA;Edward and Alphonse Elric are two brothers gifted with the ability of alchemy, the science of taking one thing and changing it into another. However, alchemy works on the theory of Equivalent Exchange -- for something to be created, something else of equal value must be sacrificed. When their mother dies, Edward decides to do the unthinkable -- bringing her back to life by breaking one of Alchemy's biggest taboos and performing Human Alchemy. Thinking they have nothing more to lose, he and Alphonse make their attempt -- but something goes horribly wrong. In the process, Alphonse loses his body and Edward loses his leg. Ed manages to save Al by attaching his spirit to a suit of armor, but at the cost of his arm and leg." index="1" rating="8.8" year="2004" thumb="/library/metadata/1882/thumb?t=1343971818" art="/library/metadata/1882/art?t=1343971818" banner="/library/metadata/1882/banner?t=1343971818" theme="/library/metadata/1882/theme?t=1343971818" duration="1800000" originallyAvailableAt="2004-11-01" leafCount="52" viewedLeafCount="52" addedAt="1343971030" updatedAt="1343971818">
			  <Genre tag="Action and Adventure"/>
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="1260" key="/library/metadata/1260/children" type="show" title="Galaxy Angel" contentRating="TV-PG" summary="The Galaxy Angel anime series, produced by BROCCOLI, Madhouse and Bandai Visual, The story is about a group of women and girls who go on government-sponsored humanitarian missions as the Angel Troupe (Angel-tai) to search for Lost Technology, generally a plot device to set up amusing and absurd humor typical of the show, rife with obscure Japanese puns. Many of the devices look like extremely mundane objects like sticks or rice cookers, but have fantastic powers like mutating organisms or as destructive weapons.  (This is the BROADCAST order)" index="1" rating="8" year="2001" thumb="/library/metadata/1260/thumb?t=1343881576" art="/library/metadata/1260/art?t=1343881576" banner="/library/metadata/1260/banner?t=1343881576" duration="900000" originallyAvailableAt="2001-04-07" leafCount="90" viewedLeafCount="0" addedAt="1343881115" updatedAt="1343881576">
			  <Genre tag="Action and Adventure"/>
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="2240" key="/library/metadata/2240/children" studio="HBO" type="show" title="Game of Thrones" contentRating="TV-MA" summary="Based on the fantasy novel series &quot;A Song of Ice and Fire,&quot; Game of Thrones explores the story of an epic battle among seven kingdoms and two ruling families in the only game that matters - the Game of Thrones. All seek control of the Iron Throne, the possession of which ensures survival through the 40-year winter to come." index="1" rating="9.4" year="2011" tagline="When you play the game of thrones, you win or you die." thumb="/library/metadata/2240/thumb?t=1344048472" art="/library/metadata/2240/art?t=1344048472" banner="/library/metadata/2240/banner?t=1344048472" theme="/library/metadata/2240/theme?t=1344048472" duration="3600000" originallyAvailableAt="2011-04-17" leafCount="10" viewedLeafCount="10" addedAt="1344048134" updatedAt="1344048472">
			  <Genre tag="Action and Adventure"/>
			  <Genre tag="Drama"/>
			</Directory>
			<Directory ratingKey="2677" key="/library/metadata/2677/children" studio="Kids Station" type="show" title="Genshiken" summary="This is the story of college freshman Kanji Sasahara and his fellow members of the college club he joins, The Society for the Study of Modern Visual Culture (aka Genshiken), as he goes shopping for doujinshi, attends conventions and slowly but surely makes his way down the road to fandom." index="1" rating="8.8" year="2004" thumb="/library/metadata/2677/thumb?t=1344313590" art="/library/metadata/2677/art?t=1344313590" banner="/library/metadata/2677/banner?t=1344313590" duration="1500000" originallyAvailableAt="2004-10-01" leafCount="24" viewedLeafCount="24" addedAt="1344313484" updatedAt="1344313590">
			  <Genre tag="Animation"/>
			  <Genre tag="Comedy"/>
			</Directory>
			<Directory ratingKey="1937" key="/library/metadata/1937/children" studio="Tokyo Broadcasting System" type="show" title="Getbackers" contentRating="TV-14" summary="They're the Get Backers, and they live by a simple motto: If it was taken, we'll get it back.  Their success rate is 100%.  They may have no luck with money, but they always come through on a job, no matter how small.      Ban and Ginji are no ordinary retrieval service though.  With Ginji's ability to generate lightning and Ban's Jagan Eye and 200kg force grip, they'll take on any job, from retrieving stuffed toys to fine art to lost memories.  If the GetBackers say they'll get it back, they will!" index="1" rating="8.7" year="2002" thumb="/library/metadata/1937/thumb?t=1343971781" art="/library/metadata/1937/art?t=1343971781" banner="/library/metadata/1937/banner?t=1343971781" duration="1500000" originallyAvailableAt="2002-10-05" leafCount="49" viewedLeafCount="49" addedAt="1343971345" updatedAt="1343971781">
			  <Genre tag="Action and Adventure"/>
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="1357" key="/library/metadata/1357/children" studio="WOWOW" type="show" title="Ghost Hound" summary="Reality is a dream, the dreams of the night are real.&#xA;&#xA;In the world of Utsushiyo (reality), the development of an electronic brain far far away and long ago allows two different worlds to overlap.&#xA;&#xA;Within the last vestiges of Japan`s raw landscape, lies a small coastal town. In it live three middle school students: Komori Tarou, Ogami Makoto, and Nakajima Masayuki. Each holds within them a unique past that cannot be erased.&#xA;&#xA;Once more, but by different causes, three people learn that by the extraction of one`s soul, the coming and going between Utsushiyo and Kakuriyo (hidden world) is possible. Amidst the boys` adventure in Kakuriyo, they come to understand where it is is connected to.&#xA;&#xA;An eternal spiritual story is offered to the adults who possess the minds of boys.&#xA;&#xA;At last, this fall, the curtain will rise!!" index="1" rating="8" year="2007" thumb="/library/metadata/1357/thumb?t=1343881489" art="/library/metadata/1357/art?t=1343881489" banner="/library/metadata/1357/banner?t=1343881489" duration="1500000" originallyAvailableAt="2007-10-18" leafCount="22" viewedLeafCount="0" addedAt="1343881231" updatedAt="1343881489">
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="884" key="/library/metadata/884/children" studio="TV Tokyo" type="show" title="Gosick" summary="In a European country neatly tucked beside the Alps Kazuya Kujo returns from studying abroad at the prestigious Saint Marguerite Academy, where urban legends and horror stories are popular. His brainy friend, Victorique, is much more intrigued by true stories, and she uses her unrivaled logic to solve mysteries even the town's famous detective can't." index="1" rating="8.4" year="2011" thumb="/library/metadata/884/thumb?t=1343875006" art="/library/metadata/884/art?t=1343875006" banner="/library/metadata/884/banner?t=1343875006" duration="1500000" originallyAvailableAt="2011-01-07" leafCount="24" viewedLeafCount="0" addedAt="1343874953" updatedAt="1343875006">
			  <Genre tag="Animation"/>
			  <Genre tag="Drama"/>
			</Directory>
			<Directory ratingKey="2466" key="/library/metadata/2466/children" studio="AT-X" type="show" title="Gun Frontier" summary="&quot;Gun Frontier&quot; is regarded as the start point of Leiji Matsumoto`s `World Ring.` It is a hilarious, thrilling and outrageous story that takes place on a lawless planet in deep space. In a wild land where the dust of sand swirls, two totally different men, Harlock `the Quick Draw` and Tochiro `the Master Swordsman,` meet a mysterious woman called Sinunora and travel together. &quot;This odd threesome get involved in thrilling and outrageous brawls and seem to attract one fight after another!&quot;&#xA;The planet is called &quot;Gun Frontier.&quot; There is no law and order on this dry and barren star.&#xA;&#xA;To live and to die, it depends on your own aptitude. It depends how smart you are.&#xA;&#xA;This is the rule of the men`s world - &quot;Gun Frontier!&quot;&#xA;&#xA;The bullet carries a man`s dreams and a bullet blows his dreams away.&#xA;&#xA;There`s a time for a man to go for it even if he knows he`s going to die.&#xA;&#xA;There`s a time for a man to fight even if he knows he`s going to lose.&#xA;&#xA;Can our heroes survive in this harsh frontier full of danger and traps...? And what is the true purpose of Sinunora? " index="1" year="2002" thumb="/library/metadata/2466/thumb?t=1344060998" art="/library/metadata/2466/art?t=1344060998" banner="/library/metadata/2466/banner?t=1344060998" duration="1500000" originallyAvailableAt="2002-03-28" leafCount="13" viewedLeafCount="0" addedAt="1344060951" updatedAt="1344060998">
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="2704" key="/library/metadata/2704/children" studio="AT-X" type="show" title="Heaven's Memo Pad" summary="The story revolves around Narumi Fujishima - an ordinary high school boy who is isolated from his fellow classmates. One afternoon fellow classmate Ayaka Shinozaki invites Narumi to join the gardening club and introduces him a reclusive detective named Alice. Alice hires Narumi as an assistant and put him to work solving the strange mysteries of Angel Fix - an illegal drug. Little does he know it could put him and Ayaka in serious trouble." index="1" rating="9.5" year="2011" thumb="/library/metadata/2704/thumb?t=1344313607" art="/library/metadata/2704/art?t=1344313607" banner="/library/metadata/2704/banner?t=1344313607" duration="1500000" originallyAvailableAt="2011-07-02" leafCount="12" viewedLeafCount="0" addedAt="1344313493" updatedAt="1344313607">
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="1763" key="/library/metadata/1763/children" studio="Animax" type="show" title="Hell Girl" contentRating="TV-PG" summary="Somewhere in the vast sea of the Internet, there's a website that can only be accessed at the stroke of midnight. Known as the Jigoku Tsushin, rumor has it that if you post a grudge there, the Jigoku Shoujo will appear and drag whoever torments you into the inferno. Very little is known about the girl - all we know for sure is that she lives with her equally enigmatic grandmother, that three magical straw dolls accompany and serve her, and that whenever a posting on the Jigoku Tsushin moves her, she becomes the Jigoku Shoujo." index="1" rating="7.8" year="2005" thumb="/library/metadata/1763/thumb?t=1343967797" art="/library/metadata/1763/art?t=1343967797" banner="/library/metadata/1763/banner?t=1343967797" duration="1500000" originallyAvailableAt="2005-10-05" leafCount="78" viewedLeafCount="0" addedAt="1343967515" updatedAt="1343967797">
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="5840" key="/library/metadata/5840/children" type="show" title="Hellsing Ultimate" summary="Operating in modern-day London, the Hellsing Organization is dedicated of ridding England of the scourge of vampires. However, the principle weapon of this organization just happens to be a vampire himself - Alucard, who serves the organization`s young leader, the iron-willed woman Sir Integra Wingates Hellsing, as well as Alucard`s new apprentice, a young vampire woman named Seras Victoria.&#xA;&#xA;Lately, a rash of artificially-created vampires has taken the organization by surprise. As it turns out, a neo-Nazi society known as the Millennium Order is responsible for creating these vampires. Their sole purpose... to achieve what Nazi Germany couldn`t do over 60 years ago with human soldiers... the total conquest of the world!" index="1" rating="9.4" year="2006" duration="3000000" originallyAvailableAt="2006-02-10" leafCount="9" viewedLeafCount="0" addedAt="1344388703" updatedAt="1344388753">
			  <Genre tag="Action and Adventure"/>
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="910" key="/library/metadata/910/children" studio="AT-X" type="show" title="Hen Zemi" contentRating="TV-MA" summary="The pure and innocent Nanako Matsutaka is a seemingly normal girl with a normal student life, except that she’s enrolled in a Pervert Physiology Course run by the depraved Professor Meshiya! Being a naïve girl with no sexual experience and a disdain for anything perverted, Nanako is at the bottom of her class. As she attempts to avoid flunking out of the course, Nanako works alongside her classmates in order to complete her various unorthodox assignments from Professor Meshiya." index="1" rating="5" year="2010" thumb="/library/metadata/910/thumb?t=1343874995" banner="/library/metadata/910/banner?t=1343874995" duration="1500000" originallyAvailableAt="2010-07-23" leafCount="15" viewedLeafCount="13" addedAt="1343874955" updatedAt="1343874995">
			  <Genre tag="Animation"/>
			  <Genre tag="Comedy"/>
			</Directory>
			<Directory ratingKey="1506" key="/library/metadata/1506/children" studio="TV Tokyo" type="show" title="Highschool of the Dead" contentRating="TV-MA" summary="The world is over taken with a very deadly disease that turns humans into zombies. In Japan, several students of Fujimi High School, and the school nurse, band together to survive the present apocalypse. The story follows Takashi Komuro, one of the students who survived in the initial outbreak." index="1" rating="8.8" year="2010" thumb="/library/metadata/1506/thumb?t=1343958586" art="/library/metadata/1506/art?t=1343958586" banner="/library/metadata/1506/banner?t=1343958586" theme="/library/metadata/1506/theme?t=1343958586" duration="1500000" originallyAvailableAt="2010-07-05" leafCount="12" viewedLeafCount="12" addedAt="1343958370" updatedAt="1343958586">
			  <Genre tag="Action and Adventure"/>
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="1994" key="/library/metadata/1994/children" studio="Kansai TV" type="show" title="Higurashi no Naku Koro ni" contentRating="TV-MA" summary="Adaption of the amateur created murder mystery computer game Higurashi no Naku Koro Ni developed by the studio 7th Expansion. Studio Deen will produce the animation.&#xA;&#xA;The main character of the story is Maebara Keiichi, a young teenager, who has recently moved from the city to the rural village of Hinamizawa with his family. He`s adjusting pretty well to his new life, making several friends at his new and small school, playing games every day and passing his days in a bliss, when suddenly a murder case happens...&#xA;&#xA;From that point on a mystery, which traces back to happenings five years ago, begins to unravel itself before him. But which is that he is bound to find out and more importantly, will he be able to digest the truth behind all of this." index="1" rating="9.1" year="2006" thumb="/library/metadata/1994/thumb?t=1343975027" art="/library/metadata/1994/art?t=1343975027" banner="/library/metadata/1994/banner?t=1343975027" theme="/library/metadata/1994/theme?t=1343975027" duration="1500000" originallyAvailableAt="2006-04-05" leafCount="55" viewedLeafCount="1" addedAt="1343974820" updatedAt="1343975027">
			  <Genre tag="Animation"/>
			  <Genre tag="Drama"/>
			</Directory>
			<Directory ratingKey="2053" key="/library/metadata/2053/children" studio="TV Tokyo" type="show" title="His and Her Circumstances" contentRating="TV-14" summary="Pressure is high for Yukino Miyazawa to succeed, to be loved by all, and to be simply...the best. After working so hard to become the top student at her school, a new competitor has arrived to tumble her from her self made pedestal: Arima Souichirou. The instant she met him, she hated him. He topped her every effort without even trying. Now Yukino is putting her hard work into plotting her revenge, but was love part of the plan?" index="1" rating="10" year="1998" thumb="/library/metadata/2053/thumb?t=1343974982" art="/library/metadata/2053/art?t=1343974982" banner="/library/metadata/2053/banner?t=1343974982" duration="1500000" originallyAvailableAt="1998-10-01" leafCount="26" viewedLeafCount="26" addedAt="1343974860" updatedAt="1343974982">
			  <Genre tag="Animation"/>
			  <Genre tag="Comedy"/>
			</Directory>
			<Directory ratingKey="5851" key="/library/metadata/5851/children" type="show" title="Inukami!" summary="Inukami! revolves around Keita Kawahira, a descendant of a Inukami-tamer clan and considered a failure by the clan due to his attitude towards his duty. Inukami, literally &quot;dog god&quot;, are benevolent creatures that possess spiritual powers. They are a type of demon with the appearance of a dog who can transform into human form. Along with a partner from the historic Inukami-tamer clan, they act to obliterate evil and proliferate righteousness. Keita is initially unable to find an Inukami to bond with, but eventually a beautiful Inukami named Yoko decides to become his Inukami, causing Keita to become overjoyed. However, his joy is short-lived when he discovers that she is a very problematic and uncontrollable Inukami. From then on, Keita's life becomes filled with never-ending embarrassment." index="1" rating="7.8" year="2006" thumb="/library/metadata/5851/thumb?t=1344388758" art="/library/metadata/5851/art?t=1344388758" banner="/library/metadata/5851/banner?t=1344388758" duration="1500000" originallyAvailableAt="2006-04-06" leafCount="26" viewedLeafCount="0" addedAt="1344388705" updatedAt="1344388758">
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="2871" key="/library/metadata/2871/children" studio="BBC Choice, then BBC Three" type="show" title="Japanorama" summary="A BBC documentary programme where presenter Jonathan Ross travels to Japan to explore Japan's current popular culture, and how it came to be that way. Based on Jonathan Ross's love for all things Japanese, Japanorama takes the viewer through post-war Japan, showing its amazing rise from the ashes of war in movies, TV-shows, anime, manga and more." index="1" rating="10" year="2002" thumb="/library/metadata/2871/thumb?t=1344313609" art="/library/metadata/2871/art?t=1344313609" banner="/library/metadata/2871/banner?t=1344313609" theme="/library/metadata/2871/theme?t=1344313609" duration="1500000" originallyAvailableAt="2002-06-09" leafCount="18" viewedLeafCount="0" addedAt="1344313527" updatedAt="1344313609">
			  <Genre tag="News"/>
			  <Genre tag="Documentary"/>
			</Directory>
			<Directory ratingKey="209" key="/library/metadata/209/children" studio="Tokyo Broadcasting System" type="show" title="K-ON!" contentRating="TV-Y" summary="Four Japanese high school girls join their school's light music club to try to save it from being abolished. However, they are the only members of the club, and none of them have any experience playing musical instruments or reading sheet music." index="1" rating="8.7" year="2009" thumb="/library/metadata/209/thumb?t=1343792942" art="/library/metadata/209/art?t=1343792942" banner="/library/metadata/209/banner?t=1343792942" theme="/library/metadata/209/theme?t=1343792942" duration="1500000" originallyAvailableAt="2009-04-03" leafCount="32" viewedLeafCount="32" addedAt="1343792892" updatedAt="1343792942">
			  <Genre tag="Animation"/>
			  <Genre tag="Comedy"/>
			</Directory>
			<Directory ratingKey="1381" key="/library/metadata/1381/children" studio="Fuji TV" type="show" title="Katanagatari" summary="The historical epic centers on Shichika Yasuri, the seventh generational head of the Kyotō-ryū school of martial arts in medieval Japan. He and his older sister Nanami live on an isolated island, until a military advisor named Togame tells him of the final 12 swords forged by a legendary swordsmith. At Togame's bidding, Shichika embarks on a journey to find all 12 of the swords." index="1" rating="9.4" year="2010" thumb="/library/metadata/1381/thumb?t=1343881484" art="/library/metadata/1381/art?t=1343881484" banner="/library/metadata/1381/banner?t=1343881484" theme="/library/metadata/1381/theme?t=1343881484" duration="3000000" originallyAvailableAt="2010-01-26" leafCount="12" viewedLeafCount="7" addedAt="1343881250" updatedAt="1343881484">
			  <Genre tag="Action and Adventure"/>
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="971" key="/library/metadata/971/children" type="show" title="Kiddy Girl-and" summary="ES members Éclair and Lumière once were involved in a battle to decide the fate of the galaxy. They prevailed and peace was restored. Now, 25 years later, the galaxy once again stands on the brink of chaos. This conflict will see the dawn of two new heroines; Ascoeur and Q-feuille. The two girls work for the galactic government known as GTO, as they are training to become members of ES." index="1" rating="5" year="2009" thumb="/library/metadata/971/thumb?t=1343875091" art="/library/metadata/971/art?t=1343875091" banner="/library/metadata/971/banner?t=1343875091" theme="/library/metadata/971/theme?t=1343875091" duration="1500000" originallyAvailableAt="2009-10-15" leafCount="24" viewedLeafCount="24" addedAt="1343874960" updatedAt="1343875091">
			  <Genre tag="Action and Adventure"/>
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="997" key="/library/metadata/997/children" studio="Fuji TV" type="show" title="Kiddy Grade" summary="In the distant future, humans have rapidly spread across the galaxy, creating thousands of independent planetary states. However, as humans begin to dominate solar systems, the scale of the skirmishes between planets escalates.&#xA;&#xA;The Intergalactic Planetary Federation (IPF) was established to maintain peace and stability, to promote economic prosperity and to head off the threat of large-scale war. An era of peace prevails, but as each solar system begins to prosper, so do economic markets, which become the new battlegrounds. The IPF then establishes a new organization called the Galactic Organization of Trade and Tariffs (GOTT) to oversee fair trade among the aggressively competing planetary states. Enter our two heroines, GOTT receptionists Eclair and Lumiere - but you soon find out that receptionist is just their cover, because they`re really secret agents of Encounter of Shadow-work (ES), working on important economic dispute resolutions assigned by their boss Eclipse.&#xA;&#xA;Flying a hi-speed space cruiser, together with Donnershlag, their guardian robot, Éclair and Lumiere solve problems between planets and organizations. Although their exploits are always thrilling, traps lurk in unexpected places, waiting to ensnare the unwary.&#xA;&#xA;Our heroines have special abilities. Éclair is a beautiful battle titan and Lumiere has sophisticated computer-like information processing abilities. Working as secret agents of the Galactic Organization of Trade and Tariffs (GOTT), the two work to resolve disputes planets and organizations, sometimes brilliantly and other times disasterously. With international spy-like action and meticulously planned SF setups, this is a true SF action story! This is the first work by director Keiji Gotoh, the character designer for Nadesico the Mission and Gatekeepers. " index="1" rating="8" year="2002" thumb="/library/metadata/997/thumb?t=1343875099" art="/library/metadata/997/art?t=1343875099" banner="/library/metadata/997/banner?t=1343875099" duration="1500000" originallyAvailableAt="2002-10-01" leafCount="24" viewedLeafCount="24" addedAt="1343874962" updatedAt="1343875099">
			  <Genre tag="Animation"/>
			  <Genre tag="Science-Fiction"/>
			</Directory>
			<Directory ratingKey="2718" key="/library/metadata/2718/children" studio="Tokyo Broadcasting System" type="show" title="Kill Me Baby" summary="Kill Me Baby follows the comedic life of a typical school girl Yasuna and her assassin classmate Sonya. Sonya's attempt to fit in often fails when her natural assassin instincts kick in and Yasuna's attempt to be more friendly with Sonya often gets her hurt or intimidated." index="1" rating="7.7" year="2012" thumb="/library/metadata/2718/thumb?t=1344313602" art="/library/metadata/2718/art?t=1344313602" banner="/library/metadata/2718/banner?t=1344313602" duration="1500000" originallyAvailableAt="2012-01-06" leafCount="13" viewedLeafCount="0" addedAt="1344313495" updatedAt="1344313602">
			  <Genre tag="Animation"/>
			  <Genre tag="Comedy"/>
			</Directory>
			<Directory ratingKey="57" key="/library/metadata/57/children" studio="NTV" type="show" title="Kimi ni Todoke" summary="Sawako Kuronuma, called Sadako by her classmates for her resemblance to the character from The Ring, has always been feared and misunderstood because of her appearance. There are rumors that Sawako can see ghosts and curse people. However, despite her appearances, she is a sweet and timid girl who longs to be able to make friends with everyone and be like everyone else. When her idol, popular boy Kazehaya, begins talking with her, everything changes. She finds herself in a new world, trying to make friends and talking to different people and she can't thank Kazehaya enough for giving her these opportunities. Slowly, but surely, a sweet love is blossoming between the two as they will overtake any circumstance or clear obstacles in their way." index="1" rating="8.3" year="2009" thumb="/library/metadata/57/thumb?t=1343788588" art="/library/metadata/57/art?t=1343788588" banner="/library/metadata/57/banner?t=1343788588" theme="/library/metadata/57/theme?t=1343788588" duration="1500000" originallyAvailableAt="2009-10-07" leafCount="25" viewedLeafCount="0" addedAt="1343788542" updatedAt="1343788588">
			  <Genre tag="Animation"/>
			  <Genre tag="Comedy"/>
			</Directory>
			<Directory ratingKey="2206" key="/library/metadata/2206/children" type="show" title="Kujibiki Unbalance" summary="Once a year prestigious Rikkyouin High School has a lottery to determine the next year's Student Council membership. On their first day of school Chihiro Enomoto wins the presidency while his childhood friend Tokino Akiyama picks the vice-president's ticket. There is one catch though, they must first pass a one year apprenticeship under the current Student Council and any failure to perform the tasks assigned, however minor, will result in immediate expulsion from the school." index="1" year="2006" thumb="/library/metadata/2206/thumb?t=1344048494" art="/library/metadata/2206/art?t=1344048494" banner="/library/metadata/2206/banner?t=1344048494" duration="1500000" originallyAvailableAt="2006-10-06" leafCount="12" viewedLeafCount="0" addedAt="1344047692" updatedAt="1344048494">
			  <Genre tag="Animation"/>
			  <Genre tag="Comedy"/>
			</Directory>
			<Directory ratingKey="1064" key="/library/metadata/1064/children" studio="TV Tokyo" type="show" title="Level E" summary="In the present day, hundreds of extraterrestrial species walk the Earth. Some are pacifistic, others violent. Some are here for research purposes, others are career criminals. However, humans don't know they are here.&#xA;&#xA;Now, one more alien has arrived on Earth. One of the universe's foremost geniuses with a personality that's bound to attract all sorts of trouble. " index="1" rating="8" year="2011" thumb="/library/metadata/1064/thumb?t=1343877679" art="/library/metadata/1064/art?t=1343877679" banner="/library/metadata/1064/banner?t=1343877679" duration="1500000" originallyAvailableAt="2011-01-11" leafCount="13" viewedLeafCount="0" addedAt="1343877570" updatedAt="1343877679">
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="139" key="/library/metadata/139/children" studio="NTV" type="show" title="Lupin III - The Woman Called Fujiko Mine" contentRating="TV-MA" summary="Many people are falling prey to a suspicious new religion. Lupin III infiltrates this group, hoping to steal the treasure their leader keeps hidden. There he lays eyes on the beautiful, bewitching woman who has the leader enthralled. This is the story of how fashionable female thief Fujiko Mine first met Lupin III, the greatest theif of his generation." index="1" rating="8" year="2012" thumb="/library/metadata/139/thumb?t=1343789029" art="/library/metadata/139/art?t=1343789029" banner="/library/metadata/139/banner?t=1343789029" duration="1500000" originallyAvailableAt="2012-04-04" leafCount="13" viewedLeafCount="0" addedAt="1343789017" updatedAt="1343789029">
			  <Genre tag="Action and Adventure"/>
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="2322" key="/library/metadata/2322/children" studio="CTC" type="show" title="Magical Girl Lyrical Nanoha" contentRating="TV-14" summary="Yuuno Scraia is a mage from a distant planet working to fix the problem he started when Jewel Seeds were accidentally spread around the world. In a failed attempt to seal a seed properly, he winds up on Earth in the form of a ferret. However, his battle with the seeds did not end upon reaching the Earth and he needs somebody else's help to seal the seeds for him. Takamachi Nanoha hears his telepathic cries for help and comes to his rescue. When she is given a pearl known as the Raging Heart she is able to transform into Magical Girl Lyrical Nanoha and wield a staff to fend off the evil that lies within the Seeds. In order to help Yuuno complete his mission, she needs to seal all 21 Jewel Seeds away, but Fate may be playing a hand in the matter to prevent Nanoha's goals." index="1" rating="10" year="2004" thumb="/library/metadata/2322/thumb?t=1344054074" art="/library/metadata/2322/art?t=1344054074" banner="/library/metadata/2322/banner?t=1344054074" duration="1500000" originallyAvailableAt="2004-01-10" leafCount="52" viewedLeafCount="52" addedAt="1344053783" updatedAt="1344054074">
			  <Genre tag="Action and Adventure"/>
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="1079" key="/library/metadata/1079/children" studio="TV Tokyo" type="show" title="Mai-HiME" summary="Mai Tokiha transfers to Fuka Academy and learns that she along with several other girls at the school are HiMEs. Initially, the girls face off against monsters and a nefarious foreign organization. But when they learn of their true purpose at Fuka Academy, the girls must fight to save the world and protect what's most important to them." index="1" rating="7.9" year="2004" thumb="/library/metadata/1079/thumb?t=1343953922" art="/library/metadata/1079/art?t=1343953922" banner="/library/metadata/1079/banner?t=1343953922" theme="/library/metadata/1079/theme?t=1343953922" duration="1800000" originallyAvailableAt="2004-09-30" leafCount="54" viewedLeafCount="54" addedAt="1343877572" updatedAt="1343953922">
			  <Genre tag="Action and Adventure"/>
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="1136" key="/library/metadata/1136/children" studio="TV Tokyo" type="show" title="Mai-Otome" summary="Adapted from its predecessor Mai-HiME, this series is not a direct sequel, but an alternate universe setting, featuring some of the Mai-HiME cast (though with different personalities).&#xA;&#xA;Arika Yumemiya is a poor yet energetic girl who has come to the city to become an Otome – a female warrior with the power to match an entire army. She quickly befriends her irritable fellow student Nina Wong and Princess Mashiro, the queen-to-be. With the help of her mysterious benefactor and abundant natural talent, she’s able to overcome the trials of everyday life in the competitive Garderobe Academy, but darker schemes are afoot. How will her new friendships fare, when secrets of the past and present are brought forth to spark a fight for the crown, and more?" index="1" rating="8" year="2005" thumb="/library/metadata/1136/thumb?t=1343877705" art="/library/metadata/1136/art?t=1343877705" banner="/library/metadata/1136/banner?t=1343877705" duration="1500000" originallyAvailableAt="2005-10-06" leafCount="33" viewedLeafCount="33" addedAt="1343877579" updatedAt="1343877705">
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="942" key="/library/metadata/942/children" studio="Tokyo Broadcasting System" type="show" title="Maid Sama!" summary="The romantic comedy centers on the student council head named Ayuzawa Misaki who despises the mostly male, slovenly population at her school, which was once an all-boys school. However, Misaki's most handsome schoolmate just discovered her secret — that she works after school at a maid cafe." index="1" rating="9.3" year="2010" thumb="/library/metadata/942/thumb?t=1343875099" art="/library/metadata/942/art?t=1343875099" banner="/library/metadata/942/banner?t=1343875099" duration="1500000" originallyAvailableAt="2010-04-01" leafCount="27" viewedLeafCount="0" addedAt="1343874958" updatedAt="1343875099">
			  <Genre tag="Animation"/>
			  <Genre tag="Comedy"/>
			</Directory>
			<Directory ratingKey="5879" key="/library/metadata/5879/children" studio="CTC" type="show" title="Maria Holic" summary="The story centers on a sophomore named Kanako who enrolls in all-girls school because she has a phobia of men and wants to find her destined yuri partner. She meets a captivating freshman named Mariya who fits her criteria — except her seemingly ideal mate happens to be a cross-dressing sadistic boy." index="1" rating="7.7" year="2009" thumb="/library/metadata/5879/thumb?t=1344388761" art="/library/metadata/5879/art?t=1344388761" banner="/library/metadata/5879/banner?t=1344388761" duration="1500000" originallyAvailableAt="2009-01-04" leafCount="24" viewedLeafCount="0" addedAt="1344388711" updatedAt="1344388761">
			  <Genre tag="Animation"/>
			  <Genre tag="Comedy"/>
			</Directory>
			<Directory ratingKey="113" key="/library/metadata/113/children" studio="MBS" type="show" title="Mawaru Penguindrum" summary="The story centres around the lives of three siblings, Takakura Kanba, Takakura Shouma and their terminally ill sister Takakura Himari. Himari passes away after going out on a trip with her brothers. She was however, miraculously saved by a spirit thriving in a penguin-shaped hat. In return for her extended life, the twins must search for an item known as the Penguin Drum with the aid of three penguins which are visible only to the siblings.&#xA;" index="1" rating="9.3" year="2011" thumb="/library/metadata/113/thumb?t=1343788618" art="/library/metadata/113/art?t=1343788618" duration="1500000" originallyAvailableAt="2011-07-03" leafCount="24" viewedLeafCount="0" addedAt="1343788546" updatedAt="1343788618">
			  <Genre tag="Animation"/>
			  <Genre tag="Comedy"/>
			</Directory>
			<Directory ratingKey="2587" key="/library/metadata/2587/children" studio="CTC" type="show" title="The Melancholy of Haruhi Suzumiya" titleSort="Melancholy of Haruhi Suzumiya" contentRating="TV-PG" summary="On the first day of high school a beautiful girl named Haruhi Suzumiya introduces herself as having &quot;no interest in ordinary humans&quot;. She asks for any aliens, time travelers, sliders or espers to join her. Watching her weird behaviour is Kyon a boy who sits in front of Haruhi and is the only person who talks to her. Commenting on Haruhi's joining every club in school and then quitting Kyon unwittingly gives Haruhi an idea to start her own after school club. Thereafter Kyon and several others find themselves literally dragged into the Save our world by Overloading it with fun Suzumiya Haruhi's Brigade (the S.O.S. Brigade for short)." index="1" rating="9" year="2006" thumb="/library/metadata/2587/thumb?t=1344305616" art="/library/metadata/2587/art?t=1344305616" banner="/library/metadata/2587/banner?t=1344305616" theme="/library/metadata/2587/theme?t=1344305616" duration="1500000" originallyAvailableAt="2006-02-04" leafCount="28" viewedLeafCount="0" addedAt="1344305300" updatedAt="1344305616">
			  <Genre tag="Animation"/>
			  <Genre tag="Comedy"/>
			</Directory>
			<Directory ratingKey="2893" key="/library/metadata/2893/children" studio="ABC Family" type="show" title="The Middleman" titleSort="Middleman" contentRating="TV-14" summary="The Middleman is based on the comic book by Javier Grillo-Marxauch (Medium, The Chronicle), The show follows Wendy Watson (Natalie Morales) when she get recruited by a secret agency, directed by the Middleman. Together they fight mad scientist, evil supervillains, ghosts, ghouls, zombies, and science experiments gone wild." index="1" rating="8.3" year="2008" thumb="/library/metadata/2893/thumb?t=1344313621" art="/library/metadata/2893/art?t=1344313621" banner="/library/metadata/2893/banner?t=1344313621" duration="3600000" originallyAvailableAt="2008-06-16" leafCount="12" viewedLeafCount="12" addedAt="1344313532" updatedAt="1344313621">
			  <Genre tag="Drama"/>
			  <Genre tag="Science-Fiction"/>
			</Directory>
			<Directory ratingKey="2269" key="/library/metadata/2269/children" studio="TV Asahi" type="show" title="Mobile Suit Gundam Wing" contentRating="TV-14" summary="Mankind has moved into space. Thousands of people live on giant orbiting space colonies called &quot;Sides.&quot; However, the Earth Government, which rules the colonies, is unjust and cruel. A group of revolutionaries builds five robotic weapons called Gundams and plans to send them to Earth to begin their fight for independence. Piloted by five young men, these Gundams carry the hopes and dreams of freedom of the colonists with them as they descend to Earth to begin Operation Meteor!" index="1" rating="8.6" year="1995" thumb="/library/metadata/2269/thumb?t=1344053939" art="/library/metadata/2269/art?t=1344053939" banner="/library/metadata/2269/banner?t=1344053939" duration="1500000" originallyAvailableAt="1995-04-07" leafCount="50" viewedLeafCount="50" addedAt="1344053760" updatedAt="1344053939">
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="382" key="/library/metadata/382/children" studio="CBS" type="show" title="The Muppet Show" titleSort="Muppet Show" contentRating="TV-G" summary="The Muppet Show is a British-American television programme produced by puppeteer Jim Henson and featuring Muppets. After two pilot episodes were produced in 1974 and 1975, the show premiered on September 5, 1976 and five series were produced until March 15, 1981, lasting 120 episodes. The programme shows a vaudeville- or music hall-style song-and-dance variety show, as well as glimpses behind the scenes of such a show. Kermit the Frog stars as a showrunner who tries to keep control of the antics of the other Muppet characters (and his temper), as well as keep the guest stars happy. The show was known for outrageous physical slapstick, sometimes absurdist comedy, and humorous parodies. Each episode also featured a human guest star. As the shows popularity rose, many celebrities were eager to perform with the Muppets on television and in film." index="1" rating="8.5" year="1976" thumb="/library/metadata/382/thumb?t=1343863857" art="/library/metadata/382/art?t=1343863857" banner="/library/metadata/382/banner?t=1343863857" theme="/library/metadata/382/theme?t=1343863857" duration="1800000" originallyAvailableAt="1976-09-01" leafCount="119" viewedLeafCount="0" addedAt="1343863769" updatedAt="1343863857">
			  <Genre tag="Children"/>
			  <Genre tag="Comedy"/>
			</Directory>
			<Directory ratingKey="2560" key="/library/metadata/2560/children" studio="ABC" type="show" title="Muppets Tonight" summary="&quot;Muppets Tonight!&quot; was a short lived new version of the classic 'The Muppet Show', that hoped to appeal to a new generation.  This series continued with several traditions that the original series did.  Each episode revolved around a celebrity guest and there were new Muppet skits throughout the show. New Muppets are introduced throughout the series who would later appear in the newer Muppet films.  The show itself gains a new host as Kermit the Frog passes the torch to a new Muppet named Clifford who hosts the show. In February 2004, Disney Enterprises bought two major Jim Henson properties: the Muppets and Bear in the Big Blue House. &quot;Muppets Tonight!&quot; premiered its first 10 episodes on ABC.  The remaining episodes aired on the Disney Channel until the show's cancellation." index="1" rating="8" year="1996" thumb="/library/metadata/2560/thumb?t=1344303281" art="/library/metadata/2560/art?t=1344303281" banner="/library/metadata/2560/banner?t=1344303281" duration="1800000" originallyAvailableAt="1996-03-01" leafCount="22" viewedLeafCount="0" addedAt="1344303241" updatedAt="1344303281">
			  <Genre tag="Children"/>
			</Directory>
			<Directory ratingKey="2102" key="/library/metadata/2102/children" studio="TV Tokyo" type="show" title="Neon Genesis Evangelion" contentRating="TV-14" summary="In the year 2015, the Angels, huge, tremendously powerful, alien war machines, appear in Tokyo for the second time. The only hope for Mankind`s survival lies in the Evangelion, a humanoid fighting machine developed by NERV, a special United Nations agency. Capable of withstanding anything the Angels can dish out, the Evangelion`s one drawback lies in the limited number of people able to pilot them. Only a handful of teenagers, all born fourteen years ago, nine months after the Angels first appeared, are able to interface with the Evangelion. One such teenager is Shinji Ikari, whose father heads the NERV team that developed and maintains the Evangelion. Thrust into a maelstrom of battle and events that he does not understand, Shinji is forced to plumb the depths of his own inner resources for the courage and strength to not only fight, but to survive, or risk losing everything." index="1" rating="9.3" year="1995" thumb="/library/metadata/2102/thumb?t=1343975006" art="/library/metadata/2102/art?t=1343975006" banner="/library/metadata/2102/banner?t=1343975006" theme="/library/metadata/2102/theme?t=1343975006" duration="1500000" originallyAvailableAt="1995-10-04" leafCount="27" viewedLeafCount="27" addedAt="1343974910" updatedAt="1343975006">
			  <Genre tag="Action and Adventure"/>
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="1023" key="/library/metadata/1023/children" type="show" title="Nyanpire" summary="The TV anime series Nyanpire The Animation is created by studio Gonzo, based on Yukiusa's doujinshi The Gothic World of Nyanpire, about a vampire cat. The story follows a black cat who was abandoned and left to starve. Just before the cat's life was to be extinguished, a vampire emerged from the darkness and gave it blood. Now, &quot;Nyanpire&quot; lives as a seemingly ordinary house cat raised by a human girl." index="1" rating="8" year="2011" thumb="/library/metadata/1023/thumb?t=1343875128" art="/library/metadata/1023/art?t=1343875128" duration="300000" originallyAvailableAt="2011-07-06" leafCount="12" viewedLeafCount="12" addedAt="1343874964" updatedAt="1343875128">
			  <Genre tag="Animation"/>
			  <Genre tag="Children"/>
			</Directory>
			<Directory ratingKey="2481" key="/library/metadata/2481/children" studio="BBC Two" type="show" title="Oz and James's Big Wine Adventure" summary="Oz and James's Big Wine Adventure is a television series first broadcast by the BBC in the autumn of 2006. It is accompanied by a book. &#xA;&#xA;The programme is presented by wine expert Oz Clarke and motoring journalist James May (of Top Gear fame), the former taking it upon himself to educate the latter about wine, in particular French wine. For several weeks, they travel around France's wine regions in an 1989 Jaguar XJ-S convertible. &#xA;&#xA;Although at times it gets quite technical, the programme is light in tone, much of its entertainment value deriving from the personality clashes between the refined gourmet Clarke and May, whom the former at one point describes as &quot;an utter scruff&quot;. (This is ironic given that on Top Gear May has a habit of positioning himself as the gentleman of the three presenters.)&#xA;&#xA;May is a far from ideal student and often behaves rather rudely and grumpily, being more interested in drinking wine than in talking about it. When he thinks Oz starts rambling too much, May blows on a whistle, dubbed the &quot;Ozillator&quot; (a pun on oscillator).&#xA;&#xA;At the beginning of their journey, May is someone who likes to drink wine, but knows next to nothing about it. Clarke teaches him the basics about smells and texture and about grape varieties, shows him how wine is made, what wine goes with what food and also focuses the culture surrounding wine. The two visit wine makers of all kinds, from ones in small sheds to prestigious operations like Champagne Krug. Clarke quizzes May a few times, often with embarrassing results, but ultimately May does pick up certain things." index="1" rating="8" year="2006" thumb="/library/metadata/2481/thumb?t=1344061006" art="/library/metadata/2481/art?t=1344061006" banner="/library/metadata/2481/banner?t=1344061006" duration="1800000" originallyAvailableAt="2006-11-22" leafCount="13" viewedLeafCount="3" addedAt="1344060966" updatedAt="1344061006">
			  <Genre tag="Documentary"/>
			</Directory>
			<Directory ratingKey="1188" key="/library/metadata/1188/children" studio="Tokyo MX" type="show" title="Panty &amp; Stocking with Garterbelt" summary="A company of ghosts has moved into Daten City, taking advantage of human greed. Two angels, Panty and Stocking, are sent from heaven to exterminate them -- but in reality they got kicked out for bad behavior." index="1" rating="7.3" year="2010" thumb="/library/metadata/1188/thumb?t=1343877711" art="/library/metadata/1188/art?t=1343877711" banner="/library/metadata/1188/banner?t=1343877711" theme="/library/metadata/1188/theme?t=1343877711" duration="1500000" originallyAvailableAt="2010-10-01" leafCount="14" viewedLeafCount="14" addedAt="1343877588" updatedAt="1343877711">
			  <Genre tag="Animation"/>
			  <Genre tag="Comedy"/>
			</Directory>
			<Directory ratingKey="1203" key="/library/metadata/1203/children" studio="NHK" type="show" title="Planetes" contentRating="TV-PG" summary="It is the year 2075. In a world where travelling between Earth, Space stations and the moon has become normal.&#xA;&#xA;Hachimaki (Hoshino Hachirouta) is just an ordinary salaryman. He works at a space station collecting debris. However, he has a dream of owning his very own space ship someday. And so he is spending his days collecting debris together with his colleagues Yuri, Fee and his friend Tanabe. Now it is his fourth year doing that work and he is going to be 25 years old soon, which is why he starts to think about his life.&#xA;&#xA;How does Hachimaki feel? Well, today, Hachimaki is going to do the same job..." index="1" rating="9.1" year="2003" thumb="/library/metadata/1203/thumb?t=1343877739" art="/library/metadata/1203/art?t=1343877739" banner="/library/metadata/1203/banner?t=1343877739" duration="1500000" originallyAvailableAt="2003-10-04" leafCount="26" viewedLeafCount="0" addedAt="1343877591" updatedAt="1343877739">
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="2498" key="/library/metadata/2498/children" studio="WOWOW" type="show" title="Please Teacher!" summary="Kei Kusanagi is an average high-school student living with his aunt and uncle. One night while he is sitting by a lake, he becomes &quot;stuck&quot;. When he is stuck he goes into a coma like state for a moment. After he awakens from being &quot;stuck&quot; he sees a weird disturbance on the water. After the disturbance disappears he sees a woman appear from a ray of light right. It's an alien. The next day he learns that the mysterious woman is his new homeroom teacher and his neighbor. Later, he is forced to marry her to keep her secret. Thus, a romantic comedy is born." index="1" rating="8.5" year="2002" thumb="/library/metadata/2498/thumb?t=1344104308" art="/library/metadata/2498/art?t=1344104308" banner="/library/metadata/2498/banner?t=1344104308" duration="1500000" originallyAvailableAt="2002-01-10" leafCount="13" viewedLeafCount="13" addedAt="1344104226" updatedAt="1344104308">
			  <Genre tag="Animation"/>
			  <Genre tag="Comedy"/>
			</Directory>
			<Directory ratingKey="2220" key="/library/metadata/2220/children" studio="WOWOW" type="show" title="Please Twins!" summary="The second installment from the popular series Onegai Teacher. The main character of the story is Kamishiro Maiku, a high school student who is recently lost his parents and is living alone. &#xA; He eventually meets Miyafuji Miina and Onodera Karen, whom are both claiming that they are his twin. However, these two girls have completely different personalities, and in fact are opposite to each other. This onegai/please is a romantic drama between three people so please expect elements of the like. This is a modern day twist on a classic US TV show, Three's Company. This being the second installment, you may want to consider getting a copy of Onegai Sensai for full enjoyment of the series." index="1" rating="8.3" year="2003" thumb="/library/metadata/2220/thumb?t=1344048657" art="/library/metadata/2220/art?t=1344048657" banner="/library/metadata/2220/banner?t=1344048657" duration="1500000" originallyAvailableAt="2003-07-01" leafCount="13" viewedLeafCount="13" addedAt="1344047888" updatedAt="1344048657">
			  <Genre tag="Animation"/>
			  <Genre tag="Comedy"/>
			</Directory>
			<Directory ratingKey="99" key="/library/metadata/99/children" studio="Tokyo Broadcasting System" type="show" title="Puella Magi Madoka Magica" summary="There exist familiars who have the power to grant one wish to a chosen girl. However, that girl must then become a Puella Magi, a girl with magical powers, and fight against witches, evil creatures born from curses that are responsible for murders and suicides. A schoolgirl named Madoka Kaname and her friend Sayaka Miki are approached by a familiar named Kyubey and Puella Magi named Mami Tomoe with offers of becoming magical girls. Another Peulla Magi named Homura Akemi tries to prevent Madoka from making such a deal." index="1" rating="9" year="2011" thumb="/library/metadata/99/thumb?t=1343788594" art="/library/metadata/99/art?t=1343788594" banner="/library/metadata/99/banner?t=1343788594" theme="/library/metadata/99/theme?t=1343788594" duration="1500000" originallyAvailableAt="2011-01-06" leafCount="12" viewedLeafCount="12" addedAt="1343788545" updatedAt="1343788594">
			  <Genre tag="Animation"/>
			  <Genre tag="Fantasy"/>
			</Directory>
			<Directory ratingKey="2513" key="/library/metadata/2513/children" studio="AT-X" type="show" title="Queen's Blade" contentRating="TV-MA" summary="In 4 years time the competition that will decide who the next Queen shall be will start. The strongest warrior will continue to rule the country according to tradition and expand it. The contestants need only be older than 12 years. They need not be human, intelligent or even of that country. The rules for the tournament are simple: murder is allowed. Any weapon can be chosen. The winner is decided when one of the participants flees or can't move anymore. Such event is broadcasted trough a crystal sphere by the court's magic teacher to all population to see and enjoy." index="1" rating="7" year="2009" thumb="/library/metadata/2513/thumb?t=1344111414" art="/library/metadata/2513/art?t=1344111414" banner="/library/metadata/2513/banner?t=1344111414" theme="/library/metadata/2513/theme?t=1344111414" duration="1500000" originallyAvailableAt="2009-04-02" leafCount="42" viewedLeafCount="0" addedAt="1344111362" updatedAt="1344111414">
			  <Genre tag="Action and Adventure"/>
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="2235" key="/library/metadata/2235/children" type="show" title="Re: Cutie Honey" contentRating="TV-14" summary="A mysterious organization known as Panther Claw make their presence known by terrorizing Tokyo and giving the cops a run for their money. Police are further baffled by the appearance of a lone cosplaying vigilante who thwarts all of Panther Claw's evil schemes before disappearing. That cosplayer is Honey Kisaragi, the result of the late Professor Kisaragi's prize experiment. A master of disguise, Honey can magically alter her physical appearance and outfits. But with a push of the heart-shaped button on her choker, she transforms herself into Cutie Honey, the scantily-clad, sword-wielding warrior of love and justice." index="1" rating="9" year="2004" thumb="/library/metadata/2235/thumb?t=1344048513" art="/library/metadata/2235/art?t=1344048513" duration="2700000" originallyAvailableAt="2004-12-21" leafCount="3" viewedLeafCount="0" addedAt="1344047980" updatedAt="1344048513">
			  <Genre tag="Action and Adventure"/>
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="753" key="/library/metadata/753/children" type="show" title="Revolutionary Girl Utena" summary="Utena Tenjou`s parents died when she was a little girl. At that time, a prince appeared to her and gave her a signet ring with a rose crest. He told Utena to keep the ring and promised that they would meet again someday. Utena was so impressed by him that she decided to become a prince herself! Utena is all grown up now. She studies at the Ohtori Academy and wears her own version of the boys` uniform. She still looks forward to finding her prince, but in the meantime, it`s up to Utena to save damsels in distress and cross swords with Ohtori Academy`s top duelists. When Utena unwittingly wins the &quot;Rose Bride&quot; in one such duel, she finds herself in the middle of something else... something that just may lead her to her prince." index="1" rating="9.3" year="1997" thumb="/library/metadata/753/thumb?t=1343871333" art="/library/metadata/753/art?t=1343871333" banner="/library/metadata/753/banner?t=1343871333" duration="1500000" originallyAvailableAt="1997-04-02" leafCount="39" viewedLeafCount="39" addedAt="1343871306" updatedAt="1343871333">
			  <Genre tag="Animation"/>
			  <Genre tag="Fantasy"/>
			</Directory>
			<Directory ratingKey="272" key="/library/metadata/272/children" studio="Tokyo Broadcasting System" type="show" title="Sankarea" contentRating="TV-PG" summary="Furuya is obsessed with zombies. He collects any figurines, watches any movie, and plays any game with the living dead, and is even only interested in zombie girls. When his cat dies, Furuya begins trying to raise it from the dead using an ancient book of the occult he bought from a shop. But what will happen when he sees the idol of a nearby all girl's school walking close to where he conducts his experiment, wishing to die and be reborn as a different person?" index="1" rating="9.2" year="2012" thumb="/library/metadata/272/thumb?t=1343795751" art="/library/metadata/272/art?t=1343795751" banner="/library/metadata/272/banner?t=1343795751" duration="1500000" originallyAvailableAt="2012-04-05" leafCount="12" viewedLeafCount="12" addedAt="1343795723" updatedAt="1343795751">
			  <Genre tag="Animation"/>
			  <Genre tag="Comedy"/>
			</Directory>
			<Directory ratingKey="1395" key="/library/metadata/1395/children" studio="TV Asahi" type="show" title="Sora no Otoshimono" contentRating="TV-14" summary="Sakurai Tomoki is a normal student whose motto is &quot;Normal is the best&quot;. If there is one thing abnormal, it is that he often dreams of a girl whose face he cannot even remember, and when he wakes up from that dream, he would always be crying. He tried leaving it as just a dream... but one day, from the sky, an angel descended." index="1" rating="9.8" year="2009" thumb="/library/metadata/1395/thumb?t=1343881515" art="/library/metadata/1395/art?t=1343881515" banner="/library/metadata/1395/banner?t=1343881515" duration="1500000" originallyAvailableAt="2009-10-05" leafCount="26" viewedLeafCount="0" addedAt="1343881323" updatedAt="1343881515">
			  <Genre tag="Animation"/>
			  <Genre tag="Comedy"/>
			</Directory>
			<Directory ratingKey="1423" key="/library/metadata/1423/children" studio="TV Tokyo" type="show" title="Sound of the Sky" summary="Set in the future on a land that, after being marred by long-lasting wars, has settled into a quiet cycle of decline. Kanata Kumika is a 15-year-old girl who fulfills her dream of enlisting in the army and joins a unit of five girls who protect a fortress that looms over a little village. The girls also play music that reverberates across the skies over towns without people and seas without fish.&#xA;&#xA;This title is reported as using the Spanish city of Cuenca and its nearby Alarcón Fortress as a model for the storyline. " index="1" rating="8.3" year="2010" thumb="/library/metadata/1423/thumb?t=1343881525" art="/library/metadata/1423/art?t=1343881525" banner="/library/metadata/1423/banner?t=1343881525" theme="/library/metadata/1423/theme?t=1343881525" duration="1500000" originallyAvailableAt="2010-01-05" leafCount="14" viewedLeafCount="0" addedAt="1343881359" updatedAt="1343881525">
			  <Genre tag="Animation"/>
			  <Genre tag="Science-Fiction"/>
			</Directory>
			<Directory ratingKey="313" key="/library/metadata/313/children" studio="CTC" type="show" title="Strike Witches" summary="When humanity is threatened by an alien menace, when all other options have been exhausted, mankind’s last line of defence will not be tanks, planes, or battleships – rather, it will be brave young girls who take to the skies to fight for the planet!&#xA;&#xA;Set in a world that’s both familiar and yet strangely different to our own, STRIKE WITCHES revolves around a team of girls with magical powers, who wear special fighter plane equipment in order to fight in thrilling aerial battles. In this world, the Industrial Revolution was powered by magic rather than steam - and the Wright Sisters invented a magical aircraft to replace broomsticks.&#xA;&#xA;Following the progress of these girls through this bitter war, STRIKE WITCHES will chart their triumphs, their tragedies, their friendships and their rivalries. In a world torn asunder by war, these innocent young women come of age on the battlefield - all against the backdrop of some of the most stunning aerial battles ever seen in any visual medium.&#xA;&#xA;Thrilling battles, superb mecha and high drama– STRIKE WITCHES delivers in full on the promise of Japanese animation!" index="1" rating="9" year="2008" thumb="/library/metadata/313/thumb?t=1343795771" art="/library/metadata/313/art?t=1343795771" banner="/library/metadata/313/banner?t=1343795771" duration="1500000" originallyAvailableAt="2008-07-03" leafCount="24" viewedLeafCount="0" addedAt="1343795725" updatedAt="1343795771">
			  <Genre tag="Action and Adventure"/>
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="340" key="/library/metadata/340/children" studio="Tokyo MX" type="show" title="Tiger &amp; Bunny" summary="Sternbild City is home to people called &quot;Next,&quot; who use their special abilities to protect the people as superheroes. These heroes solve cases and save lives so they can wear sponsor logos or acquire &quot;hero points.&quot; Their activities are documented on the popular program &quot;Hero TV,&quot; which picks the &quot;King of Heroes&quot; in a yearly ranking. The veteran hero Wild Tiger has always preferred to work alone, but now he's been assigned the rookie Barnaby Brooks Jr., who has a different perspective on being a superhero" index="1" rating="8.4" year="2011" thumb="/library/metadata/340/thumb?t=1343795772" art="/library/metadata/340/art?t=1343795772" banner="/library/metadata/340/banner?t=1343795772" theme="/library/metadata/340/theme?t=1343795772" duration="1500000" originallyAvailableAt="2011-04-03" leafCount="25" viewedLeafCount="0" addedAt="1343795727" updatedAt="1343795772">
			  <Genre tag="Action and Adventure"/>
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="2747" key="/library/metadata/2747/children" studio="Tokyo Broadcasting System" type="show" title="To Love-Ru" contentRating="TV-14" summary="The story is about Yuuki Rito, a high-school boy who cannot confess to the girl of his dreams, Sairenji Haruna. One day when coming home and sulking in the bath-tub a mysterious, nude girl, appears out of nowhere. Her name is Lala and she comes from the planet Deviluke, where she is the heir to the throne. Her father wants her to return to her home planet so she can marry one of the husband candidates, but she decides that she wants to marry Rito in order to stay on Earth." index="1" rating="7.9" year="2008" thumb="/library/metadata/2747/thumb?t=1344313635" art="/library/metadata/2747/art?t=1344313635" banner="/library/metadata/2747/banner?t=1344313635" duration="1500000" originallyAvailableAt="2008-04-03" leafCount="44" viewedLeafCount="0" addedAt="1344313506" updatedAt="1344313635">
			  <Genre tag="Animation"/>
			  <Genre tag="Comedy"/>
			</Directory>
			<Directory ratingKey="1735" key="/library/metadata/1735/children" studio="Tokyo MX" type="show" title="Valkyria Chronicles" summary="Set in an alternate timeline of Europe in 1930s, the country of Gallia has come under attack by East European Imperial Alliance who value the country's abundance of ragnite ore—which can be refined into a powerful fuel. Welkin Gunther, son of Gallian war hero General Belgen Gunther, leads a team of soldiers in a desperate bid reclaim their war-torn neutral nation from enemy control." index="1" rating="8.4" year="2009" thumb="/library/metadata/1735/thumb?t=1343969185" art="/library/metadata/1735/art?t=1343969185" banner="/library/metadata/1735/banner?t=1343969185" theme="/library/metadata/1735/theme?t=1343969185" duration="1500000" originallyAvailableAt="2009-04-05" leafCount="26" viewedLeafCount="0" addedAt="1343964896" updatedAt="1343969185">
			  <Genre tag="Action and Adventure"/>
			  <Genre tag="Animation"/>
			</Directory>
			<Directory ratingKey="2907" key="/library/metadata/2907/children" studio="Sci-Fi" type="show" title="Who Wants to Be a Superhero?" summary="The SCI FI Channel and legendary comic-book creator Stan Lee present a six-episode, one-hour weekly reality series that will challenge contestants to create their very own superhero. &#xA;&#xA;Potential contestants have been asked to audition with their idea for a superhero, including a self-made costume. From thousands of hopefuls, Stan Lee has chosen eleven to star in the series. The chosen ones are asked to leave their former lives behind and move into a “secret lair” and begin their transformation into their superhero identity. &#xA;&#xA;Every week, under the watchful eye of Stan Lee, the superheroes will be asked to test their skills, discover their true nature and prove themself as a superhero. Each week Stan will decide over who will stay in the lair and who will have to go home.&#xA;&#xA;In the end, only one will remain, and that person will be invited to appear, as their character, in an original SCI FI Channel movie." index="1" year="2006" thumb="/library/metadata/2907/thumb?t=1344313623" art="/library/metadata/2907/art?t=1344313623" banner="/library/metadata/2907/banner?t=1344313623" duration="3600000" originallyAvailableAt="2006-07-27" leafCount="14" viewedLeafCount="14" addedAt="1344313537" updatedAt="1344313623">
			  <Genre tag="Reality"/>
			  <Genre tag="Science-Fiction"/>
			</Directory>
			<Directory ratingKey="508" key="/library/metadata/508/children" studio="ABC" type="show" title="Whose Line Is It Anyway" contentRating="TV-PG" summary="Whose Line Is It Anyway? (1998-2004) is a continuation of the British show of the same name which aired from 1988 to 1998 with many of the same performers. It features some of the nation's finest improvisational comedians, including Florida's Wayne Brady, Canada's Colin Mochrie, and Ryan Stiles and Drew Carey from The Drew Carey Show. Each week, the preceding four and a rotating group of actors and actresses spontaneously played games with outrageous scenes, weird quirks, or (sometimes off-key) songs." index="1" rating="9.4" year="1998" thumb="/library/metadata/508/thumb?t=1343863918" art="/library/metadata/508/art?t=1343863918" banner="/library/metadata/508/banner?t=1343863918" duration="1800000" originallyAvailableAt="1998-08-01" leafCount="219" viewedLeafCount="219" addedAt="1343863776" updatedAt="1343863918">
			  <Genre tag="Comedy"/>
			</Directory>
			<Directory ratingKey="2432" key="/library/metadata/2432/children" studio="MBS" type="show" title="Xam'd: Lost Memories" summary="Akiyuki, the main character of the animated series, lives on Sentan Island, a land that has preserved its status as a free and peaceful island in a world consumed by fighting between the Northern and Southern Governments. All of this changes when Akiyuki boards a bus along with a mysterious white-haired girl who transforms his arm with the lost memories and power of Xam'd.&#xA;&#xA;As Xam'd, Akiyuki goes on a rampage and is saved when a foreign girl with red hair named &quot;Nakiami&quot; calms him down, taking him back to her postal vessel. Akiyuki now must gain control of his powers and use them against the Northern Government's latest weapons, known as &quot;Humanforms&quot;. Traveling the world on a postal vessel, Akiyuki hopes to return home one day, but until then he befriends other passengers on the boat." index="1" rating="9.7" year="2008" thumb="/library/metadata/2432/thumb?t=1344053957" art="/library/metadata/2432/art?t=1344053957" banner="/library/metadata/2432/banner?t=1344053957" theme="/library/metadata/2432/theme?t=1344053957" duration="1500000" originallyAvailableAt="2008-07-15" leafCount="26" viewedLeafCount="0" addedAt="1344053836" updatedAt="1344053957">
			  <Genre tag="Action and Adventure"/>
			  <Genre tag="Animation"/>
			</Directory>
		  </MediaContainer>
			*/
		
		/*
		<MediaContainer size="78" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1343722542" nocache="1" sortAsc="1" viewGroup="show" viewMode="458803" art="/:/resources/show-fanart.jpg" title1="TV Shows" title2="All Shows" identifier="com.plexapp.plugins.library">
			<Directory type="show"/>
			<Directory type="show"/>
			<Directory type="show"/>
		</MediaContainer>
		*/
		
		public function parse(value:Object):Vector.<Show> {
			
		}
		
		//----------------------------------------
		//
		// Constructor
		//
		//----------------------------------------
		
		public function ShowSectionParser() {
			
		}
	}
}